#!/usr/bin/env node
/**
 * Build the two published halves from `src/` without a bundler.
 *
 * `lib/index.js` is the host half verbatim (valid ESM as authored).
 *
 * `lib/client.js` is the client half wrapped in DSH's dynamic-Client package
 * envelope: a single `window.__ModuleLoader__.load({ id, factory })` script
 * whose factory body is the concatenation of `src/client/*.js` in the order
 * listed below. Those sources are deliberately plain scripts that share one
 * top-level scope and end with `module.exports = { apply, inject }`, so no
 * transform, no dependency graph and no transpiler are involved — the build
 * only concatenates and wraps, which keeps the generated bundle inspectable.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))

/** Concatenation order; every later file may use names bound by earlier ones. */
const CLIENT_SOURCES = [
  'src/client/data.js',
  'src/client/art.js',
  'src/client/styles.js',
  'src/client/settings.js',
  'src/client/mascot.js',
  'src/client/index.js',
]

const banner = `window.__ModuleLoader__.load({ id: '${pkg.name}', factory: (require) => {`
const header = `var module = { exports: {} };
var exports = module.exports;
/* Generated by scripts/build.mjs — edit src/client/*.js, not this file. */`

/* Offline PNG snapshots avoid network requests and continuously decoded WebP
   animation. Only lightweight CSS transforms animate the couple. */
const artwork = {}
for (const name of ['couple-brand', 'couple-home', 'couple-hug', 'couple-cheer']) {
  artwork[name] = `data:image/png;base64,${(await readFile(join(root, 'static/art', `${name}.png`))).toString('base64')}`
}
const bodies = [`const COUPLE_ARTWORK = Object.freeze(${JSON.stringify(artwork)});`]
for (const relative of CLIENT_SOURCES) {
  const source = await readFile(join(root, relative), 'utf8')
  bodies.push(`/* ===== ${relative} ===== */\n${source.trimEnd()}`)
}

const client = `${banner}
${header}
${bodies.join('\n\n')}

module.exports = { apply, inject };
return module.exports; } });
`

await mkdir(join(root, 'lib'), { recursive: true })
await writeFile(join(root, 'lib/client.js'), client)
await writeFile(join(root, 'lib/index.js'), await readFile(join(root, 'src/index.js'), 'utf8'))

const bytes = Buffer.byteLength(client)
console.log(`built lib/client.js (${bytes} bytes) and lib/index.js`)
